project:
  type: website
  output-dir: docs

website:
  title: "My Website"
  navbar:
    left:
      - href: projects.qmd
        text: Projects
      - icon: linkedin
        href: https://www.linkedin.com/in/matthew-huang-67b835231/
      - icon: github
        href: https://github.com/Ambrois
      - href: https://ambrois.github.io/webby/
        text: Recursion
format:
  html:
    theme: flatly
    css: styles.css

editor: source