---
title: "Narrative Visualization (Scratch)"
author: "Matthew Huang"
format: html
editor: visual
---

```{r}
#| echo: false
#| output: false
library(tidyverse)
age_gaps <- read_csv("age_gaps.csv")
```

```{r}
#| fig-cap: "Figure 1.2 shows the age differences in holywood movie couples. It's clear that male older relationships are significantly more common than female older relationships, as well as having larger average age gaps."
counts_male <- age_gaps |> 
  filter(character_1_gender == "man") |> 
  count(age_difference)
counts_female <- age_gaps |> 
  filter(character_1_gender == "woman") |> 
  count(age_difference)

ggplot() +
  geom_col(data = counts_male, aes(x = age_difference, y = n), fill = "steelblue", width=1) +
  geom_col(data = counts_female, aes(x = age_difference, y = -n), fill = "pink", width=1) +
  geom_label(aes(x=30, y=40, label="Male"), color="steelblue")+
  geom_label(aes(x=30, y=-20, label="Female"), color="pink")+
  labs(title = "Age Differences in Movie Couples",
       subtitle = "By Gender of the Older Actor",
       x='', y='',
       caption = "Data sourced from hollywoodagegap.com.") +
  theme_minimal()
```

```{r}
age_gaps <- age_gaps |>
  mutate(maleFemDiff = case_when(
    character_1_gender == "woman" ~ -1 * age_difference,
    character_1_gender == "man" ~ age_difference
  ))

ggplot() +
  geom_histogram(data = age_gaps %>% filter(maleFemDiff >= 0), aes(x = maleFemDiff), fill = "steelblue", binwidth = 1) +
  geom_histogram(data = age_gaps %>% filter(maleFemDiff < 0), aes(x = maleFemDiff), fill = "pink", binwidth = 1) +
  geom_label(aes(x =20, y = 35, label = "Male"), color = "steelblue") +
  geom_label(aes(x = -20, y = 35, label = "Female"), color = "pink")+
    labs(
    title = "Age Differences in Heterosexual Movie Couples",
    subtitle = "By age of Male character - Female character",
    y="Count",
    x="Male age - Female age")+
  theme_minimal()
```

```{r}
# normality check:
qqnorm(age_gaps$maleFemDiff)
qqline(age_gaps$maleFemDiff)

# t.test
t.test(age_gaps$maleFemDiff, mu=0, alternative="greater")

```
